package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name="areas"
    ,catalog="quimirespel"
)
public class Areas  implements java.io.Serializable {


     private Long idArea;
     private String descripcion;

    public Areas() {
    }

    public Areas(String descripcion) {
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArea", unique=true, nullable=false)
    public Long getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Long idArea) {
        this.idArea = idArea;
    }

    
    @Column(name="Descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


