package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name="cargos"
    ,catalog="quimirespel"
)
public class Cargos  implements java.io.Serializable {


     private Long idCargo;
     private String descripcion;

    public Cargos() {
    }

    public Cargos(String descripcion) {
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCargo", unique=true, nullable=false)
    public Long getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Long idCargo) {
        this.idCargo = idCargo;
    }

    
    @Column(name="Descripcion", nullable=false, length=120)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


