package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CiudadesId generated by hbm2java
 */
@Embeddable
public class CiudadesId  implements java.io.Serializable {


     private long idCiudad;
     private long departamentoId;

    public CiudadesId() {
    }

    public CiudadesId(long idCiudad, long departamentoId) {
       this.idCiudad = idCiudad;
       this.departamentoId = departamentoId;
    }
   


    @Column(name="idCiudad", nullable=false)
    public long getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(long idCiudad) {
        this.idCiudad = idCiudad;
    }


    @Column(name="Departamento_id", nullable=false)
    public long getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(long departamentoId) {
        this.departamentoId = departamentoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CiudadesId) ) return false;
		 CiudadesId castOther = ( CiudadesId ) other; 
         
		 return (this.getIdCiudad()==castOther.getIdCiudad())
 && (this.getDepartamentoId()==castOther.getDepartamentoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdCiudad();
         result = 37 * result + (int) this.getDepartamentoId();
         return result;
   }   


}


