package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ciudades generated by hbm2java
 */
@Entity
@Table(name="ciudades"
    ,catalog="quimirespel"
)
public class Ciudades  implements java.io.Serializable {


     private CiudadesId id;
     private String nombre;

    public Ciudades() {
    }

    public Ciudades(CiudadesId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCiudad", column=@Column(name="idCiudad", nullable=false) ), 
        @AttributeOverride(name="departamentoId", column=@Column(name="Departamento_id", nullable=false) ) } )
    public CiudadesId getId() {
        return this.id;
    }
    
    public void setId(CiudadesId id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


