package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="quimirespel"
)
public class Departamento  implements java.io.Serializable {


     private long idDepartamento;
     private String nombre;

    public Departamento() {
    }

    public Departamento(long idDepartamento, String nombre) {
       this.idDepartamento = idDepartamento;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="idDepartamento", unique=true, nullable=false)
    public long getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="Nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


