package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Embalajes generated by hbm2java
 */
@Entity
@Table(name="embalajes"
    ,catalog="quimirespel"
)
public class Embalajes  implements java.io.Serializable {


     private Long idEmbalaje;
     private String descripcion;

    public Embalajes() {
    }

    public Embalajes(String descripcion) {
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEmbalaje", unique=true, nullable=false)
    public Long getIdEmbalaje() {
        return this.idEmbalaje;
    }
    
    public void setIdEmbalaje(Long idEmbalaje) {
        this.idEmbalaje = idEmbalaje;
    }

    
    @Column(name="Descripcion", length=120)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


