package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name="empleados"
    ,catalog="quimirespel"
)
public class Empleados  implements java.io.Serializable {


     private EmpleadosId id;
     private String nombre;
     private String apellido;
     private String documento;
     private Date fechanacimiento;
     private String telefonoFijo;
     private String telefonoMovil;
     private String email;

    public Empleados() {
    }

	
    public Empleados(EmpleadosId id, String nombre, String apellido, String documento, Date fechanacimiento, String telefonoMovil) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.documento = documento;
        this.fechanacimiento = fechanacimiento;
        this.telefonoMovil = telefonoMovil;
    }
    public Empleados(EmpleadosId id, String nombre, String apellido, String documento, Date fechanacimiento, String telefonoFijo, String telefonoMovil, String email) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.documento = documento;
       this.fechanacimiento = fechanacimiento;
       this.telefonoFijo = telefonoFijo;
       this.telefonoMovil = telefonoMovil;
       this.email = email;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEmpleado", column=@Column(name="idEmpleado", nullable=false) ), 
        @AttributeOverride(name="ciudadesId", column=@Column(name="Ciudades_id", nullable=false) ), 
        @AttributeOverride(name="cargosId", column=@Column(name="Cargos_id", nullable=false) ), 
        @AttributeOverride(name="tipoDocumentoId", column=@Column(name="TipoDocumento_id", nullable=false) ), 
        @AttributeOverride(name="areasId", column=@Column(name="Areas_id", nullable=false) ) } )
    public EmpleadosId getId() {
        return this.id;
    }
    
    public void setId(EmpleadosId id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=120)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=120)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Documento", nullable=false, length=45)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fechanacimiento", nullable=false, length=10)
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    
    @Column(name="TelefonoFijo", length=45)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    
    @Column(name="TelefonoMovil", nullable=false, length=45)
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }

    
    @Column(name="Email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


