package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormatosdetalleId generated by hbm2java
 */
@Embeddable
public class FormatosdetalleId  implements java.io.Serializable {


     private long idFormatoDetalle;
     private long estadoMaterialId;
     private long embalajesId;
     private long unidadesId;
     private long formatosEncabezadoId;

    public FormatosdetalleId() {
    }

    public FormatosdetalleId(long idFormatoDetalle, long estadoMaterialId, long embalajesId, long unidadesId, long formatosEncabezadoId) {
       this.idFormatoDetalle = idFormatoDetalle;
       this.estadoMaterialId = estadoMaterialId;
       this.embalajesId = embalajesId;
       this.unidadesId = unidadesId;
       this.formatosEncabezadoId = formatosEncabezadoId;
    }
   


    @Column(name="idFormatoDetalle", nullable=false)
    public long getIdFormatoDetalle() {
        return this.idFormatoDetalle;
    }
    
    public void setIdFormatoDetalle(long idFormatoDetalle) {
        this.idFormatoDetalle = idFormatoDetalle;
    }


    @Column(name="EstadoMaterial_id", nullable=false)
    public long getEstadoMaterialId() {
        return this.estadoMaterialId;
    }
    
    public void setEstadoMaterialId(long estadoMaterialId) {
        this.estadoMaterialId = estadoMaterialId;
    }


    @Column(name="Embalajes_id", nullable=false)
    public long getEmbalajesId() {
        return this.embalajesId;
    }
    
    public void setEmbalajesId(long embalajesId) {
        this.embalajesId = embalajesId;
    }


    @Column(name="Unidades_id", nullable=false)
    public long getUnidadesId() {
        return this.unidadesId;
    }
    
    public void setUnidadesId(long unidadesId) {
        this.unidadesId = unidadesId;
    }


    @Column(name="FormatosEncabezado_id", nullable=false)
    public long getFormatosEncabezadoId() {
        return this.formatosEncabezadoId;
    }
    
    public void setFormatosEncabezadoId(long formatosEncabezadoId) {
        this.formatosEncabezadoId = formatosEncabezadoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormatosdetalleId) ) return false;
		 FormatosdetalleId castOther = ( FormatosdetalleId ) other; 
         
		 return (this.getIdFormatoDetalle()==castOther.getIdFormatoDetalle())
 && (this.getEstadoMaterialId()==castOther.getEstadoMaterialId())
 && (this.getEmbalajesId()==castOther.getEmbalajesId())
 && (this.getUnidadesId()==castOther.getUnidadesId())
 && (this.getFormatosEncabezadoId()==castOther.getFormatosEncabezadoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdFormatoDetalle();
         result = 37 * result + (int) this.getEstadoMaterialId();
         result = 37 * result + (int) this.getEmbalajesId();
         result = 37 * result + (int) this.getUnidadesId();
         result = 37 * result + (int) this.getFormatosEncabezadoId();
         return result;
   }   


}


