package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formatosencabezado generated by hbm2java
 */
@Entity
@Table(name="formatosencabezado"
    ,catalog="quimirespel"
)
public class Formatosencabezado  implements java.io.Serializable {


     private FormatosencabezadoId id;
     private String razonSocial;
     private String nit;
     private String telefono;
     private String direccion;
     private String latitud;
     private String logitud;
     private String nombreContacto;
     private String telefonoContacto;
     private String email;
     private String numVisita;
     private Date fechaVisita;
     private Date horaVisita;
     private String especificacionSeguridad;
     private String especificacionAdicional;
     private Date fechaTempA;
     private Date fechaTempB;
     private Date fechaTempC;
     private Date fechaTempD;
     private Date horaTempA;
     private Date horaTempB;
     private Date horaTempC;
     private Date horaTempD;
     private Long enteroTempA;
     private Long enteroTempB;
     private Long enteroTempC;
     private Long enteroTempD;
     private Boolean booleanoTempA;
     private Boolean booleanoTempB;
     private Boolean booleanoTempC;
     private Boolean booleanoTempD;
     private String cadenaTempA;
     private String cadenaTempB;
     private String cadenaTempC;
     private String cadenaTempD;
     private String cadenaTempE;
     private String cadenaTempF;
     private String cadenaTempG;
     private String cadenaTempH;

    public Formatosencabezado() {
    }

	
    public Formatosencabezado(FormatosencabezadoId id, String razonSocial, String nit, String direccion, String nombreContacto, String telefonoContacto, String numVisita, Date fechaVisita, Date horaVisita) {
        this.id = id;
        this.razonSocial = razonSocial;
        this.nit = nit;
        this.direccion = direccion;
        this.nombreContacto = nombreContacto;
        this.telefonoContacto = telefonoContacto;
        this.numVisita = numVisita;
        this.fechaVisita = fechaVisita;
        this.horaVisita = horaVisita;
    }
    public Formatosencabezado(FormatosencabezadoId id, String razonSocial, String nit, String telefono, String direccion, String latitud, String logitud, String nombreContacto, String telefonoContacto, String email, String numVisita, Date fechaVisita, Date horaVisita, String especificacionSeguridad, String especificacionAdicional, Date fechaTempA, Date fechaTempB, Date fechaTempC, Date fechaTempD, Date horaTempA, Date horaTempB, Date horaTempC, Date horaTempD, Long enteroTempA, Long enteroTempB, Long enteroTempC, Long enteroTempD, Boolean booleanoTempA, Boolean booleanoTempB, Boolean booleanoTempC, Boolean booleanoTempD, String cadenaTempA, String cadenaTempB, String cadenaTempC, String cadenaTempD, String cadenaTempE, String cadenaTempF, String cadenaTempG, String cadenaTempH) {
       this.id = id;
       this.razonSocial = razonSocial;
       this.nit = nit;
       this.telefono = telefono;
       this.direccion = direccion;
       this.latitud = latitud;
       this.logitud = logitud;
       this.nombreContacto = nombreContacto;
       this.telefonoContacto = telefonoContacto;
       this.email = email;
       this.numVisita = numVisita;
       this.fechaVisita = fechaVisita;
       this.horaVisita = horaVisita;
       this.especificacionSeguridad = especificacionSeguridad;
       this.especificacionAdicional = especificacionAdicional;
       this.fechaTempA = fechaTempA;
       this.fechaTempB = fechaTempB;
       this.fechaTempC = fechaTempC;
       this.fechaTempD = fechaTempD;
       this.horaTempA = horaTempA;
       this.horaTempB = horaTempB;
       this.horaTempC = horaTempC;
       this.horaTempD = horaTempD;
       this.enteroTempA = enteroTempA;
       this.enteroTempB = enteroTempB;
       this.enteroTempC = enteroTempC;
       this.enteroTempD = enteroTempD;
       this.booleanoTempA = booleanoTempA;
       this.booleanoTempB = booleanoTempB;
       this.booleanoTempC = booleanoTempC;
       this.booleanoTempD = booleanoTempD;
       this.cadenaTempA = cadenaTempA;
       this.cadenaTempB = cadenaTempB;
       this.cadenaTempC = cadenaTempC;
       this.cadenaTempD = cadenaTempD;
       this.cadenaTempE = cadenaTempE;
       this.cadenaTempF = cadenaTempF;
       this.cadenaTempG = cadenaTempG;
       this.cadenaTempH = cadenaTempH;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idFormatoEncabezado", column=@Column(name="idFormatoEncabezado", nullable=false) ), 
        @AttributeOverride(name="empleadosId", column=@Column(name="Empleados_id", nullable=false) ), 
        @AttributeOverride(name="tipoFormatoId", column=@Column(name="TipoFormato_id", nullable=false) ), 
        @AttributeOverride(name="ciiuId", column=@Column(name="CIIU_id", nullable=false) ) } )
    public FormatosencabezadoId getId() {
        return this.id;
    }
    
    public void setId(FormatosencabezadoId id) {
        this.id = id;
    }

    
    @Column(name="RazonSocial", nullable=false, length=150)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="Nit", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="Telefono", length=100)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Direccion", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Latitud", length=150)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="Logitud", length=150)
    public String getLogitud() {
        return this.logitud;
    }
    
    public void setLogitud(String logitud) {
        this.logitud = logitud;
    }

    
    @Column(name="NombreContacto", nullable=false, length=180)
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    
    @Column(name="TelefonoContacto", nullable=false, length=120)
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }

    
    @Column(name="Email", length=120)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="NumVisita", nullable=false, length=45)
    public String getNumVisita() {
        return this.numVisita;
    }
    
    public void setNumVisita(String numVisita) {
        this.numVisita = numVisita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaVisita", nullable=false, length=10)
    public Date getFechaVisita() {
        return this.fechaVisita;
    }
    
    public void setFechaVisita(Date fechaVisita) {
        this.fechaVisita = fechaVisita;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraVisita", nullable=false, length=8)
    public Date getHoraVisita() {
        return this.horaVisita;
    }
    
    public void setHoraVisita(Date horaVisita) {
        this.horaVisita = horaVisita;
    }

    
    @Column(name="EspecificacionSeguridad", length=260)
    public String getEspecificacionSeguridad() {
        return this.especificacionSeguridad;
    }
    
    public void setEspecificacionSeguridad(String especificacionSeguridad) {
        this.especificacionSeguridad = especificacionSeguridad;
    }

    
    @Column(name="EspecificacionAdicional", length=260)
    public String getEspecificacionAdicional() {
        return this.especificacionAdicional;
    }
    
    public void setEspecificacionAdicional(String especificacionAdicional) {
        this.especificacionAdicional = especificacionAdicional;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaTempA", length=10)
    public Date getFechaTempA() {
        return this.fechaTempA;
    }
    
    public void setFechaTempA(Date fechaTempA) {
        this.fechaTempA = fechaTempA;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaTempB", length=10)
    public Date getFechaTempB() {
        return this.fechaTempB;
    }
    
    public void setFechaTempB(Date fechaTempB) {
        this.fechaTempB = fechaTempB;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaTempC", length=10)
    public Date getFechaTempC() {
        return this.fechaTempC;
    }
    
    public void setFechaTempC(Date fechaTempC) {
        this.fechaTempC = fechaTempC;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaTempD", length=10)
    public Date getFechaTempD() {
        return this.fechaTempD;
    }
    
    public void setFechaTempD(Date fechaTempD) {
        this.fechaTempD = fechaTempD;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraTempA", length=8)
    public Date getHoraTempA() {
        return this.horaTempA;
    }
    
    public void setHoraTempA(Date horaTempA) {
        this.horaTempA = horaTempA;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraTempB", length=8)
    public Date getHoraTempB() {
        return this.horaTempB;
    }
    
    public void setHoraTempB(Date horaTempB) {
        this.horaTempB = horaTempB;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraTempC", length=8)
    public Date getHoraTempC() {
        return this.horaTempC;
    }
    
    public void setHoraTempC(Date horaTempC) {
        this.horaTempC = horaTempC;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraTempD", length=8)
    public Date getHoraTempD() {
        return this.horaTempD;
    }
    
    public void setHoraTempD(Date horaTempD) {
        this.horaTempD = horaTempD;
    }

    
    @Column(name="EnteroTempA")
    public Long getEnteroTempA() {
        return this.enteroTempA;
    }
    
    public void setEnteroTempA(Long enteroTempA) {
        this.enteroTempA = enteroTempA;
    }

    
    @Column(name="EnteroTempB")
    public Long getEnteroTempB() {
        return this.enteroTempB;
    }
    
    public void setEnteroTempB(Long enteroTempB) {
        this.enteroTempB = enteroTempB;
    }

    
    @Column(name="EnteroTempC")
    public Long getEnteroTempC() {
        return this.enteroTempC;
    }
    
    public void setEnteroTempC(Long enteroTempC) {
        this.enteroTempC = enteroTempC;
    }

    
    @Column(name="EnteroTempD")
    public Long getEnteroTempD() {
        return this.enteroTempD;
    }
    
    public void setEnteroTempD(Long enteroTempD) {
        this.enteroTempD = enteroTempD;
    }

    
    @Column(name="BooleanoTempA")
    public Boolean getBooleanoTempA() {
        return this.booleanoTempA;
    }
    
    public void setBooleanoTempA(Boolean booleanoTempA) {
        this.booleanoTempA = booleanoTempA;
    }

    
    @Column(name="BooleanoTempB")
    public Boolean getBooleanoTempB() {
        return this.booleanoTempB;
    }
    
    public void setBooleanoTempB(Boolean booleanoTempB) {
        this.booleanoTempB = booleanoTempB;
    }

    
    @Column(name="BooleanoTempC")
    public Boolean getBooleanoTempC() {
        return this.booleanoTempC;
    }
    
    public void setBooleanoTempC(Boolean booleanoTempC) {
        this.booleanoTempC = booleanoTempC;
    }

    
    @Column(name="BooleanoTempD")
    public Boolean getBooleanoTempD() {
        return this.booleanoTempD;
    }
    
    public void setBooleanoTempD(Boolean booleanoTempD) {
        this.booleanoTempD = booleanoTempD;
    }

    
    @Column(name="CadenaTempA", length=260)
    public String getCadenaTempA() {
        return this.cadenaTempA;
    }
    
    public void setCadenaTempA(String cadenaTempA) {
        this.cadenaTempA = cadenaTempA;
    }

    
    @Column(name="CadenaTempB", length=260)
    public String getCadenaTempB() {
        return this.cadenaTempB;
    }
    
    public void setCadenaTempB(String cadenaTempB) {
        this.cadenaTempB = cadenaTempB;
    }

    
    @Column(name="CadenaTempC", length=260)
    public String getCadenaTempC() {
        return this.cadenaTempC;
    }
    
    public void setCadenaTempC(String cadenaTempC) {
        this.cadenaTempC = cadenaTempC;
    }

    
    @Column(name="CadenaTempD", length=260)
    public String getCadenaTempD() {
        return this.cadenaTempD;
    }
    
    public void setCadenaTempD(String cadenaTempD) {
        this.cadenaTempD = cadenaTempD;
    }

    
    @Column(name="CadenaTempE", length=260)
    public String getCadenaTempE() {
        return this.cadenaTempE;
    }
    
    public void setCadenaTempE(String cadenaTempE) {
        this.cadenaTempE = cadenaTempE;
    }

    
    @Column(name="CadenaTempF", length=260)
    public String getCadenaTempF() {
        return this.cadenaTempF;
    }
    
    public void setCadenaTempF(String cadenaTempF) {
        this.cadenaTempF = cadenaTempF;
    }

    
    @Column(name="CadenaTempG", length=260)
    public String getCadenaTempG() {
        return this.cadenaTempG;
    }
    
    public void setCadenaTempG(String cadenaTempG) {
        this.cadenaTempG = cadenaTempG;
    }

    
    @Column(name="CadenaTempH", length=260)
    public String getCadenaTempH() {
        return this.cadenaTempH;
    }
    
    public void setCadenaTempH(String cadenaTempH) {
        this.cadenaTempH = cadenaTempH;
    }




}


