package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipodocumento generated by hbm2java
 */
@Entity
@Table(name="tipodocumento"
    ,catalog="quimirespel"
)
public class Tipodocumento  implements java.io.Serializable {


     private Long idTipoDocumento;
     private String codigo;
     private String tipoDocumento;

    public Tipodocumento() {
    }

    public Tipodocumento(String codigo, String tipoDocumento) {
       this.codigo = codigo;
       this.tipoDocumento = tipoDocumento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoDocumento", unique=true, nullable=false)
    public Long getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Long idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    
    @Column(name="Codigo", nullable=false, length=5)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="TipoDocumento", nullable=false, length=60)
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }




}


