package com.quimiespel.quimiespelmaven.map;
// Generated May 10, 2017 9:39:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidades generated by hbm2java
 */
@Entity
@Table(name="unidades"
    ,catalog="quimirespel"
)
public class Unidades  implements java.io.Serializable {


     private Long idUnidad;
     private String descripcion;

    public Unidades() {
    }

    public Unidades(String descripcion) {
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUnidad", unique=true, nullable=false)
    public Long getIdUnidad() {
        return this.idUnidad;
    }
    
    public void setIdUnidad(Long idUnidad) {
        this.idUnidad = idUnidad;
    }

    
    @Column(name="Descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


